url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Goldene Gans
email      : your-email@example.com #this is also the email contact forms will go to
description: "Site description"
author     : Your Name
logo: yes  #optional, defaults to site title
logo-path: assets\img\logo.png
logo-height: 70 #height in px, defaults to 52px

locale: "de" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"
